const REGISTER_PROVIDER_ERROR = 'REGISTER_PROVIDER_ERROR'
const REGISTER_NAME_ERROR = 'REGISTER_NAME_ERROR'
const REGISTER_EMAIL_OR_PASSWORD_ERROR = 'REGISTER_EMAIL_OR_PASSWORD_ERROR'
const EMAIL_IS_ALREADY_EXISTS = 'EMAIL_IS_ALREADY_EXISTS'

module.exports = {
  REGISTER_PROVIDER_ERROR,
  REGISTER_NAME_ERROR,
  REGISTER_EMAIL_OR_PASSWORD_ERROR,
  EMAIL_IS_ALREADY_EXISTS
}
