const CREATE_TRIP_ERROR = 'CREATE_TRIP_ERROR'
const GET_TRIPS_ERROR = 'GET_TRIPS_ERROR'
const GET_TRIP_ERROR = 'GET_TRIP_ERROR'
const CREATE_TRIP_DAY_ERROR = 'CREATE_TRIP_DAY_ERROR'
const GET_TRIP_DESTINATION_ERROR = 'GET_TRIP_DESTINATION_ERROR'
const UPDATE_TRIP_DESTINATION_ERROR = 'UPDATE_TRIP_DESTINATION_ERROR'
const DELETE_TRIP_DESTINATION_ERROR = 'DELETE_TRIP_DESTINATION_ERROR'

module.exports = {
  CREATE_TRIP_ERROR,
  GET_TRIPS_ERROR,
  GET_TRIP_ERROR,
  CREATE_TRIP_DAY_ERROR,
  GET_TRIP_DESTINATION_ERROR,
  UPDATE_TRIP_DESTINATION_ERROR,
  DELETE_TRIP_DESTINATION_ERROR
}
