const REGISTER_NAME_ERROR = 'REGISTER_NAME_ERROR'
const EMAIL_OR_PASSWORD_ERROR = 'EMAIL_OR_PASSWORD_ERROR'
const EMAIL_IS_ALREADY_EXISTS = 'EMAIL_IS_ALREADY_EXISTS'
const ACCOUNT_IS_NOT_EXISTS = 'ACCOUNT_IS_NOT_EXISTS'
const EMAIL_REGISTER_ERROR = 'EMAIL_REGISTER_ERROR'
const LOGIN_ERROR = 'LOGIN_ERROR'
const GET_USER_ERROR = 'GET_USER_ERROR'
const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

module.exports = {
  REGISTER_NAME_ERROR,
  EMAIL_OR_PASSWORD_ERROR,
  EMAIL_IS_ALREADY_EXISTS,
  ACCOUNT_IS_NOT_EXISTS,
  EMAIL_REGISTER_ERROR,
  LOGIN_ERROR,
  GET_USER_ERROR,
  UPDATE_USER_ERROR
}
